config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  namespace :admin do
    get '/dashboard', to: "orders#index"
    resources :users, only: [:index, :show] do
      resources :orders, only: [:show]
      post 'orders/:id', to: 'orders#cancel'
    end
    get '/users/:id/upgrade', to: "users#upgrade", as: 'upgrade_user'
    get '/merchants/:id/downgrade', to: "merchants#downgrade", as: 'downgrade_merchant'
    resources :merchants, only: [:index, :show]
    resources :orders, only: [:update]
    patch '/merchant/:merchant_id/', to: "merchants#update", as: :merchant_change_status
  end

  resources :users, only: [:create, :update]

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show], module: :profile
    post 'orders/:id', to: 'profile/orders#cancel', as: 'cancel_order'
    get '/', to: "users#show"
    get '/edit', to: "users#edit"
  end

  scope :dashboard, module: :merchants, as: :dashboard do
    resources :items, only: [:index, :destroy, :update, :new, :create, :edit]
    get '/', to: 'orders#index'
    get '/order/:id', to: 'orders#show', as: 'order'
    get '/download_current/:merchant_id', to: 'orders#current', as: :download_current
    get '/download_potential/:merchant_id', to: 'orders#potential', as: :download_potential
  end
  patch '/dashboard/:order/:item/fulfill', to: "merchants/orders#update", as: :fulfill_item

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  patch '/cart', to: 'carts#update'
  resources :carts, only: [:create]

  get '/merchants', to: "merchants#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/register', to: "users#new"

  resources :items, only: [:index, :show]
  resources :orders, only: [:create]
end

app/views/shared/_address.html.erb
<%= user.street_address %>
<%= "#{user.city}, #{user.state} #{user.zip_code}"%>

app/views/shared/_admin_item.html.erb
<%= item.name %>: <%= item.number %> sold

app/views/shared/_admin_merchant_index.html.erb
<main class="admin-merchant-index shadowed-box">
  <h1>All Merchants in the system</h1>
  <div id=graphics>
    <svg id=total-sales></svg>
  </div>
  <section class="data-table merchant-list">
  <% @merchants.each do |merchant| %>
    <section class="table-row" id="merchant-<%= merchant.id %>">
      <span class="merchant-name"><%= link_to "#{merchant.name}", admin_merchant_path(merchant) %></span>
      <span class="merchant-city">Located in <%= merchant.city %>, <%= merchant.state %></span>
      <span class="merchant-register-date">Joined the store on <%= merchant.created_at %></span>
      <% if merchant.enabled? %>
        <%= link_to "Disable this Merchant", admin_merchant_change_status_path(merchant), method: :patch, class: 'disable' %>
      <% elsif !merchant.enabled? %>
        <%= link_to "Enable this Merchant", admin_merchant_change_status_path(merchant), method: :patch, class: 'enable' %>
      <% end %>
    </section>
  <% end %>
  </section>
</main>

<script type="text/javascript">
  $(function(){
    getMerchantData();
  });
</script>

app/views/shared/_admin_nav.html.erb
<%= link_to 'Dashboard', admin_dashboard_path %>
<%= link_to 'Log Out', logout_path %>
<%= link_to 'Users', admin_users_path %>

app/views/shared/_item_form.html.erb
<% if @item.errors.any? %>
<ul>
  <% @item.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [:dashboard, @item] do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description, class: 'textarea-label' %>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :image_url, "Image URL"%>
  <%= f.text_field :image_url %>
</p>
<p>
  <%= f.label :current_price, "Price" %>
  <%= f.number_field :current_price, class: 'currency', step: 0.01, min: 0.0 %>
</p>
<p>
  <%= f.label :quantity, "Inventory" %>
  <%= f.number_field :quantity %>
</p>

  <%= f.submit "#{form_type} Item" %>

<% end %>

app/views/shared/_line_items.html.erb
<section class="order-item" id="item-<%= line.item.id %>">
  <%= image_tag "#{line.item.image_url.gsub('500x500', '100x100')}", size: "100x100" %>
  <span class="item-name">Item: <%= link_to line.item.name, item_path(line.item.id) %></span><br>
  <span class="item-price">Individual Price: <%= number_to_currency(line.ordered_price) %></span>
  <span class="item-quantity">QTY: <%= line.quantity %></span>
  <span class="item-subtotal">Subtotal: <%= number_to_currency(line.subtotal) %></span><br>
  <span class="item-description">Description: <%= line.item.description.gsub(/(.{125}).{4,}/m,'\1…') %></span>
</section>

app/views/shared/_merchant_item.html.erb
<div class="table-row merchant-item" id=<%="merchant-item-#{item.id}"%>>
  <div class="item-id"><%= item.id %></div>
  <div class="item-thumbnail"><img src=<%= item.image_url.gsub('500x500', '20x20') %> /></div>
  <div class="item-name"><%= item.name %></div>
  <div class="item-quantity"><%= item.quantity %></div>
  <div class="item-price"><%= number_to_currency(item.current_price) %></div>
  <%= link_to "Edit", edit_dashboard_item_path(item) %>
  <% if item.enabled %>
    <%= button_to "Disable", dashboard_item_path(item, enabled:false), method: :patch %>
  <% else %>
    <%= button_to "Enable", dashboard_item_path(item, enabled:true), method: :patch %>
  <% end %>
  <% unless item.ordered? %>
  <%= button_to "Delete", dashboard_item_path(item), method: :delete %>
  <% end %>
</div>

app/views/shared/_merchant_nav.html.erb
<%= link_to 'Dashboard', dashboard_path %>
<%= link_to 'Log Out', logout_path %>

app/views/shared/_nav.html.erb
<nav class="main-nav shadowed-box">
  <span class="nav-left">
    <%= link_to 'Home', root_path, class: 'home-link' %>
    <%= link_to 'Browse Items', items_path, class: 'items-link' %>
    <%= link_to 'View Merchants', merchants_path, class: 'merchants-link' %>
  </span>
  <% if current_user %>
  <span class="nav-center">Logged in as <%= current_user.name %></span>
  <% end %>
  <span class="nav-right">
    <% if current_customer? %>
    <%= link_to "Cart: #{@cart.total_count}", cart_path, class: 'cart-link' %>
    <% end %>
    <%= yield %>
  </span>
</nav>

app/views/shared/_order.html.erb
<section class="table-row user-orders" id="order-info">
  <span class="order-id">Order ID: <%= @order.id %></span>
  <span class="order-status">Order Status: <%= @order.status %></span>
  <span class="order-quantity">QTY of Items: <%= @order.total_count %></span>
  <span class="order-total">Grand Total: <%= number_to_currency(@order.total_cost) %></span>
  <span class="order-placed">Order Placed: <%= @order.created_at.strftime("%m/%d/%Y") %></span>
  <span class="order-updated">Last Updated: <%= @order.updated_at.strftime("%m/%d/%Y") %></span>
  <% if @order.pending? %>
    <%= button_to "Cancel Order" %>
  <% end %>
</section>

<% order.order_items.each do |line| %>
  <%= render 'shared/line_items', line:line %>
<% end %>

app/views/shared/_pending_order.html.erb
<div class="table-row" id=<%="order-#{order.id}"%>>
  <span class="order-id"><%= link_to "Order #{order.id}", dashboard_order_path(order) %></span>
  <span class="order-created-at">Created: <%= order.created_at %></span>
  <span class="order-cost">Cost: <%= number_to_currency(order.total_cost) %></span>
  <span class="order-item-count">Items: <%= order.total_count %></span>
</div>

app/views/shared/_regular_merchant_index.html.erb
<main class="merchants-index">
  <h1>All Merchants:</h1>


  <section class="merchant-stats shadowed-box">
    <section id="top-ten-this-month">
      <h3>Top 10 sellers this month</h3>
      <% @top_ten_sellers_this_month.each do |merchant| %>
        <li id="merchant"><%= merchant.name %> has sold <%= merchant.total_sold %> items</li>
      <% end %>
    </section>

    <section id="top-ten-last-month">
      <h3>Top 10 sellers last month</h3>
      <% @top_ten_sellers_last_month.each do |merchant| %>
        <li id="merchant"><%= merchant.name %> has sold <%= merchant.total_sold %> items</li>
      <% end %>
    </section>

    <section id="top-ten-fulfillers-this-month">
      <h3>Top 10 merchants of fulfilled orders this month</h3>
      <% @top_ten_fulfillers_this_month.each do |merchant| %>
        <li id="merchant"><%= merchant.name %></li>
      <% end %>
    </section>

    <section id="top-ten-fulfillers-last-month">
      <h3>Top 10 merchants of fulfilled orders last month</h3>
      <% @top_ten_fulfillers_last_month.each do |merchant| %>
        <li id="merchant"><%= merchant.name %></li>
      <% end %>
    </section>

    <% if current_user %>
      <section id="top-five-to-city">
        <h3>Top 5 fastest merchants to <%= current_user.city %></h3>
        <% @top_five_to_city.each do |merchant| %>
          <li id="merchant"><%= merchant.name %></li>
        <% end %>
      </section>

      <section id="top-five-to-state">
        <h3>Top 5 fastest merchants to <%= current_user.state %></h3>
        <% @top_five_to_state.each do |merchant| %>
          <li id="merchant"><%= merchant.name %></li>
        <% end %>
      </section>


    <% end %>

    <section id="top-three-sellers">
      <h3>Top 3 Merchants by Revenue </h3>
      <% @top_three_sellers.each do |merchant| %>
        <li><%= merchant.name %>, making <%= number_to_currency(merchant.total_revenue)  %> in revenue</li>
      <% end %>
    </section>

    <section id="fastest-merchants">
      <h3>Fastest Merchants</h3>
      <% @fastest_three.each do |merchant| %>
        <li><%= merchant.name %> averages <%= merchant.average_time %> days to fill orders</li>
      <% end %>
    </section>

    <section id="slowest-merchants">
      <h3>Slowest Merchants</h3>
      <% @slowest_three.each do |merchant| %>
        <li><%= merchant.name %> averages <%= merchant.average_time %> days to fill orders</li>
      <% end %>
    </section>

    <section id="top-three-cities">
      <h3>Cities with Most Orders</h3>
      <% @top_three_cities.each do |user| %>
        <li><%= user.count_of_orders %> orders have been shipped to <%= user.city %></li>
      <% end %>
    </section>

    <section id="top-three-states">
      <h3>States with Most Orders</h3>
      <% @top_three_states.each do |user| %>
        <li><%= user.count_of_orders %> orders have been shipped to <%= user.state %></li>
      <% end %>
    </section>


    <section id="3-largest-orders">
      <h3>Largest Orders</h3>
      <% @three_largest_orders.each do |order| %>
        <li>Order <%= order.id %> with <%= order.total_count %> items sold</li>
      <% end %>
    </section>
  </section>

  <section class="index-list">
    <% @merchants.each do |merchant| %>
    <section class="merchant-card card shadowed-box" id="merchant-<%= merchant.id %>">
      <p><%= merchant.name %></p>
      <p>Located in <%= merchant.city %>, <%= merchant.state %></p>
      <p>Joined the store on <%= merchant.created_at %></p>
    </section>
    <% end %>
  </section>
</main>

app/views/shared/_user_nav.html.erb
<%= link_to 'Profile', profile_path %>
<%= link_to 'Log Out', logout_path %>

app/views/shared/_visitor_nav.html.erb
<%= link_to 'Log In', '/login' %>
<%= link_to 'Register', '/register' %>