config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  namespace :admin do
    get '/dashboard', to: "orders#index"
    resources :users, only: [:index, :show] do
      resources :orders, only: [:show]
      post 'orders/:id', to: 'orders#cancel'
    end
    get '/users/:id/upgrade', to: "users#upgrade", as: 'upgrade_user'
    get '/merchants/:id/downgrade', to: "merchants#downgrade", as: 'downgrade_merchant'
    resources :merchants, only: [:index, :show]
    resources :orders, only: [:update]
    patch '/merchant/:merchant_id/', to: "merchants#update", as: :merchant_change_status
  end

  resources :users, only: [:create, :update]

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show], module: :profile
    post 'orders/:id', to: 'profile/orders#cancel', as: 'cancel_order'
    get '/', to: "users#show"
    get '/edit', to: "users#edit"
  end

  scope :dashboard, module: :merchants, as: :dashboard do
    resources :items, only: [:index, :destroy, :update, :new, :create, :edit]
    get '/', to: 'orders#index'
    get '/order/:id', to: 'orders#show', as: 'order'
    get '/download_current/:merchant_id', to: 'orders#current', as: :download_current
    get '/download_potential/:merchant_id', to: 'orders#potential', as: :download_potential
  end
  patch '/dashboard/:order/:item/fulfill', to: "merchants/orders#update", as: :fulfill_item

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  patch '/cart', to: 'carts#update'
  resources :carts, only: [:create]

  get '/merchants', to: "merchants#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/register', to: "users#new"

  resources :items, only: [:index, :show]
  resources :orders, only: [:create]
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def add_item(item_id)
    if @contents.keys.include?(item_id)
      @contents[item_id] +=1
    else
      @contents[item_id] = 1
    end
  end

  def total_count
    @contents.values.sum
  end

  def update_quantity(item_id, quantity)
    if quantity == 0
      @contents.delete(item_id)
    else
      @contents[item_id] = quantity
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_customer


  def update
    @cart.update_quantity(params[:item_id], params[:quantity].to_i)
    redirect_to cart_path
  end


  def destroy
    session[:cart] = {}
    redirect_to cart_path
  end

  def show
    @items = {}
    @cart.contents.each do |item_id, quantity|
      @items[Item.find(item_id.to_i)] = quantity
    end
    @total = @items.sum{|item,quantity| item.current_price * quantity}
  end

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id.to_s)
    session[:cart] = @cart.contents
    flash[:notice] = "You added #{item.name} to your cart"
    redirect_to items_path
  end
  private
    def require_customer
      render_404 unless current_customer?
    end
end

app/views/carts/_cart_item.html.erb
<div class="table-row cart-item" id=<%="cart-item-#{item.id}"%>>
  <div class="item-info">
    <img src=<%= item.image_url.gsub('500x500', '20x20') %> height=20px width=20px />
    <div class="item-name"><%= item.name %></div>
    <div class="item-merchant"><%= item.user.name %></div>
    <div class="item-price"><%= number_to_currency(item.current_price) %></div>
  </div>
  <div class="item-actions">
    <div class="item-quantity">
      Quantity:
      <%= form_tag cart_path(item_id: item.id), method: :patch do %>
      <%= select_tag "quantity", options_for_select((0..item.quantity).to_a, selected: quantity) %>

      <%= submit_tag "Update" %>
      <% end %>
    </div>
    <div class="item-subtotal">Subtotal: <%= number_to_currency(quantity*item.current_price) %></div>
    <div class="item-remove"><%= button_to "Remove", cart_path(item_id: item.id, quantity:0), method: :patch %></div>
  </div>
</div>

app/views/carts/show.html.erb
<main class="cart-page">
  <% if @items == {} %>
  Your cart is empty.
  <% else %>
    <section class="data-table shadowed-box">
      <% @items.each do |item, quantity| %>
        <%= render 'cart_item', item:item, quantity:quantity %>
      <% end %>
    </section>
    <div id="cart-actions">Total: <%= number_to_currency(@total) %>
      <%= button_to "Empty Cart", cart_path, method: :delete %>
      <% if current_user %>
        <%= button_to "Check Out", orders_path %>
      <% else %>
        <span class="action-required">You must <%= link_to "register", register_path %> or <%= link_to "log in", login_path %> to check out</span>
      <% end %>
    </div>
  <% end %>
</main>