config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  namespace :admin do
    get '/dashboard', to: "orders#index"
    resources :users, only: [:index, :show] do
      resources :orders, only: [:show]
      post 'orders/:id', to: 'orders#cancel'
    end
    get '/users/:id/upgrade', to: "users#upgrade", as: 'upgrade_user'
    get '/merchants/:id/downgrade', to: "merchants#downgrade", as: 'downgrade_merchant'
    resources :merchants, only: [:index, :show]
    resources :orders, only: [:update]
    patch '/merchant/:merchant_id/', to: "merchants#update", as: :merchant_change_status
  end

  resources :users, only: [:create, :update]

  scope :profile, as: :profile do
    resources :orders, only: [:index, :show], module: :profile
    post 'orders/:id', to: 'profile/orders#cancel', as: 'cancel_order'
    get '/', to: "users#show"
    get '/edit', to: "users#edit"
  end

  scope :dashboard, module: :merchants, as: :dashboard do
    resources :items, only: [:index, :destroy, :update, :new, :create, :edit]
    get '/', to: 'orders#index'
    get '/order/:id', to: 'orders#show', as: 'order'
    get '/download_current/:merchant_id', to: 'orders#current', as: :download_current
    get '/download_potential/:merchant_id', to: 'orders#potential', as: :download_potential
  end
  patch '/dashboard/:order/:item/fulfill', to: "merchants/orders#update", as: :fulfill_item

  get '/cart', to: 'carts#show'
  delete '/cart', to: 'carts#destroy'
  patch '/cart', to: 'carts#update'
  resources :carts, only: [:create]

  get '/merchants', to: "merchants#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/register', to: "users#new"

  resources :items, only: [:index, :show]
  resources :orders, only: [:create]
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name,
                        :description,
                        :image_url
  validates :quantity, presence: true, numericality:{ only_integer: true, greater_than_or_equal_to: 0}
  validates :current_price, presence: true, numericality:{ greater_than: 0}
  belongs_to :user, foreign_key: 'merchant_id'
  has_many :order_items
  has_many :orders, through: :order_items

  def self.enabled_items
    where(enabled: true, users: {enabled: true})
    .joins(:user)
    .select('items.*, users.name AS merchant_name')
  end

  def self.sort_sold(direction)
    joins(order_items: :order)
    .select("items.*, sum(order_items.quantity) as item_count")
    .where(enabled: true, orders: {status: 2})
    .group(:id)
    .order('item_count ' + direction)
    .limit(5)
  end

  def self.find_by_order(order, merchant)
    joins(order_items: :order)
    .where(items: {merchant_id: merchant.id},
          orders: {id: order.id})
    .distinct
  end

  def self.merchant_top_items(merchant)
    select("items.*, sum(order_items.quantity) AS number")
    .joins(orders: :order_items)
    .where(user:merchant)
    .where( "orders.status = ?", 2)
    .group(:id)
    .order("number DESC")
    .limit(5)
  end

  def self.items_sold(merchant)
    joins(orders: :order_items)
    .where(user:merchant)
    .where("orders.status = ?", 2)
    .sum("order_items.quantity")
  end

  def self.pct_sold(merchant)
    in_stock = Item.where(user:merchant).sum(:quantity).to_f
    ((1- (in_stock / (in_stock + items_sold(merchant))))*100).round(2)
  end

  def fullfillment_time
    order_items.where(order_items: {fulfilled: true})
               .average("order_items.updated_at - order_items.created_at")
  end

  def ordered?
    orders != []
  end

  def amount_ordered(order)
    order_items.where(order_items: {order_id: order.id})
               .sum("order_items.quantity")
  end

  def fulfilled?(order)
    order_items.where(order_items: {order_id: order.id})
               .first.fulfilled
  end

  def not_enough?
    if order_items.first.quantity > self.quantity
      return true
    else
      return false
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.enabled_items
    @top_5 = Item.sort_sold('DESC')
    @bottom_5 = Item.sort_sold('ASC')
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/merchants/items_controller.rb
class Merchants::ItemsController < Merchants::BaseController
  def index
    @items = Item.where(user: current_user)
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = current_user.items.new(item_info)
    if @item.valid?
      @item.save

      flash[:info] = "#{@item.name} Saved"
      redirect_to dashboard_items_path
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    name = @item.name
    if params[:enabled]
      @item.update(enabled: params[:enabled])
      completed_action = params[:enabled] == "true" ? "Enabled": "Disabled"
      flash[:info] = [@item.name, completed_action].join(" ")
      redirect_to dashboard_items_path
    else
      info = item_info
      if info[:image_url] == ''
        info[:image_url] = 'http://www.spore.com/static/image/500/404/515/500404515704_lrg.png'
      end
      @item.update(info)
      if @item.valid?
        flash[:info] = "#{name} Edited"
        redirect_to dashboard_items_path
      else
        render :edit
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    name = @item.name
    @item.destroy
    flash[:info] = "#{name} Deleted"
    redirect_to dashboard_items_path
  end

  private

  def item_info
    params.require(:item).permit(:name, :description, :image_url, :current_price, :quantity)
  end
end

app/views/items/index.html.erb
<main class="item-index">
  <h1>All Items:</h1>

  <section class="item-stats shadowed-box">
    <ul id="most-popular-items">
      <h3>5 Most Popular Items: </h3>
      <% @top_5.each do |item| %>
        <li id="item"><%= item.name %>: <%= item.item_count %> sold</li>
      <% end %>
    </ul>

    <ul id="least-popular-items">
      <h3>5 Least Popular Items: </h3>
      <% @bottom_5.each do |item| %>
        <li id="item"><%= item.name %>: <%= item.item_count %> sold</li>
      <% end %>
    </ul>
  </section>

  <section class="index-list">
    <% @items.each do |item| %>
      <section class="item-card card shadowed-box" id="item-<%= item.id %>">
        <%= link_to item_path(item) do %>
          <h3><%= item.name %></h3>
          <%= image_tag "#{item.image_url.gsub('500x500', '100x100')}", size: "100x100" %>
        <% end %>
        <p>Sold by: <%= item.merchant_name %></p>
        <p>Number in stock: <%= item.quantity %></p>
        <p>Price: <%= number_to_currency(item.current_price) %></p>
      </section>
    <% end %>
  </section>
</main>

app/views/items/show.html.erb
<main class="item-show shadowed-box">
  <%= image_tag "#{@item.image_url}", size: "500x500" %>
  <section class="item-details">
    <h1><%= @item.name %></h1>
    <h3>Seller: <%= @item.user.name %></h3>
    <p><%= @item.description.gsub(/\n+/, '<br/><br/>').html_safe %></p>
    <p>Price: <%= number_to_currency(@item.current_price) %></p>
    <p>Number in stock: <%= @item.quantity %></p>
    <p>Average Processing Time: <%= @item.fullfillment_time %> Day(s)</p>
    <p><%= button_to "Add to Cart", carts_path(item_id: @item.id) %></p>
  </section>
</main>